### ISSUE TITLE
Crash Homebridge

### ISSUE THREAD

**Issue by elkorleone** [seikan/homebridge-sonoff-basic-espeasy#9]
When I add an accessory in the config file, Homebridge doen't work. I reinstall the plugin and it doesn't fix the problem.
I run homebridge in a docker and had a couple of accessories working propertly till now
When I delete the items into the config file, homebridge works right, what happend???

**Comment by elkorleone** [comment]
homebridge_1_f6bb5a151577 | [5/16/2019, 12:48:20 PM] Error: The requested accessory 'SonoffBasicESPEasy' was not registered by any plugin.
homebridge_1_f6bb5a151577 |     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
homebridge_1_f6bb5a151577 |     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
homebridge_1_f6bb5a151577 |     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
homebridge_1_f6bb5a151577 |     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
homebridge_1_f6bb5a151577 |     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
homebridge_1_f6bb5a151577 |     at Module._compile (internal/modules/cjs/loader.js:701:30)
homebridge_1_f6bb5a151577 |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
homebridge_1_f6bb5a151577 |     at Module.load (internal/modules/cjs/loader.js:600:32)
homebridge_1_f6bb5a151577 |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
homebridge_1_f6bb5a151577 |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by mrmasternes** [comment]
I'm having the same issues right now, did you ever find a solution?
